### ISSUE TITLE
Unknown OpenGL error at LensFlare_ScreenSpace.cpp

### ISSUE THREAD

**Issue by andriyshevchenko** [john-chapman/GfxSamples#1]
I'm running the app for the first time and got the crash at LensFlare_ScreenSpace::initScene
```cpp
//this line
m_txEnvmap = Texture::Create("textures/env_factory.dds");
```

**Comment by john-chapman** [comment]
Hi - sorry for the very late reply I must have missed the notification.

You need to install [Git LFS](https://git-lfs.github.com/), it's required for the large data files (textures, etc.).

**Comment by andriyshevchenko** [comment]
Thanks, I will try again everithing
